### ISSUE TITLE
Screenshot missing

### ISSUE THREAD

**Issue by YogiBogie** [learn-co-curriculum/riyadh-blog#5]
The first instruction refers to a screenshot provided, but there is no screenshot shown nor is there a link to a screenshot.

**Comment by aaronkelton** [comment]
The image file is part of the files forked and cloned. I think perhaps the language should be rewritten. That tripped me up, too!

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
